
USE ROLE USERADMIN;

CREATE ROLE IF NOT EXISTS FLIGHT_LOADER       COMMENT = 'dlt: laddar rådata';
CREATE ROLE IF NOT EXISTS FLIGHT_TRANSFORMER  COMMENT = 'dbt: transformerar data';
CREATE ROLE IF NOT EXISTS FLIGHT_REPORTER     COMMENT = 'Streamlit: läser marts';
