
USE ROLE SECURITYADMIN;


GRANT USAGE ON WAREHOUSE FLIGHT_WH TO ROLE FLIGHT_LOADER;
GRANT USAGE ON WAREHOUSE FLIGHT_WH TO ROLE FLIGHT_TRANSFORMER;
GRANT USAGE ON WAREHOUSE FLIGHT_WH TO ROLE FLIGHT_REPORTER;

GRANT USAGE ON DATABASE FLIGHT_DB TO ROLE FLIGHT_LOADER;
GRANT USAGE ON DATABASE FLIGHT_DB TO ROLE FLIGHT_TRANSFORMER;
GRANT USAGE ON DATABASE FLIGHT_DB TO ROLE FLIGHT_REPORTER;

GRANT USAGE, CREATE TABLE ON SCHEMA FLIGHT_DB.RAW TO ROLE FLIGHT_LOADER;


GRANT USAGE ON SCHEMA FLIGHT_DB.RAW TO ROLE FLIGHT_TRANSFORMER;
GRANT SELECT ON ALL TABLES    IN SCHEMA FLIGHT_DB.RAW TO ROLE FLIGHT_TRANSFORMER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA FLIGHT_DB.RAW TO ROLE FLIGHT_TRANSFORMER;


GRANT USAGE, CREATE TABLE, CREATE VIEW ON SCHEMA FLIGHT_DB.STAGING TO ROLE FLIGHT_TRANSFORMER;
GRANT USAGE, CREATE TABLE, CREATE VIEW ON SCHEMA FLIGHT_DB.MARTS   TO ROLE FLIGHT_TRANSFORMER;

GRANT USAGE ON SCHEMA FLIGHT_DB.MARTS TO ROLE FLIGHT_REPORTER;
GRANT SELECT ON ALL TABLES    IN SCHEMA FLIGHT_DB.MARTS TO ROLE FLIGHT_REPORTER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA FLIGHT_DB.MARTS TO ROLE FLIGHT_REPORTER;
GRANT SELECT ON ALL VIEWS     IN SCHEMA FLIGHT_DB.MARTS TO ROLE FLIGHT_REPORTER;
GRANT SELECT ON FUTURE VIEWS  IN SCHEMA FLIGHT_DB.MARTS TO ROLE FLIGHT_REPORTER;
