

USE ROLE USERADMIN;

CREATE USER IF NOT EXISTS FLIGHT_DLT_USER
    PASSWORD = 'BYT_UT_1'
    DEFAULT_ROLE = FLIGHT_LOADER
    DEFAULT_WAREHOUSE = FLIGHT_WH
    DEFAULT_NAMESPACE = FLIGHT_DB.RAW
    MUST_CHANGE_PASSWORD = FALSE
    COMMENT = 'Servicekonto för dlt';

CREATE USER IF NOT EXISTS FLIGHT_DBT_USER
    PASSWORD = 'BYT_UT_2'
    DEFAULT_ROLE = FLIGHT_TRANSFORMER
    DEFAULT_WAREHOUSE = FLIGHT_WH
    DEFAULT_NAMESPACE = FLIGHT_DB.STAGING
    MUST_CHANGE_PASSWORD = FALSE
    COMMENT = 'Servicekonto för dbt';

CREATE USER IF NOT EXISTS FLIGHT_STREAMLIT_USER
    PASSWORD = 'BYT_UT_3'
    DEFAULT_ROLE = FLIGHT_REPORTER
    DEFAULT_WAREHOUSE = FLIGHT_WH
    DEFAULT_NAMESPACE = FLIGHT_DB.MARTS
    MUST_CHANGE_PASSWORD = FALSE
    COMMENT = 'Servicekonto för Streamlit';
