-- 06: Koppla roller till användare
-- Kedjan i Snowflake: behörighet -> roll -> användare.

USE ROLE SECURITYADMIN;

GRANT ROLE FLIGHT_LOADER      TO USER FLIGHT_DLT_USER;
GRANT ROLE FLIGHT_TRANSFORMER TO USER FLIGHT_DBT_USER;
GRANT ROLE FLIGHT_REPORTER    TO USER FLIGHT_STREAMLIT_USER;

-- Gruppmedlemmar som ska utveckla får rollerna på sina egna inloggningar:
-- GRANT ROLE FLIGHT_TRANSFORMER TO USER <KOMPISENS_ANVÄNDARNAMN>;
-- GRANT ROLE FLIGHT_REPORTER    TO USER <KOMPISENS_ANVÄNDARNAMN>;
