
USE ROLE SECURITYADMIN;

SHOW GRANTS TO ROLE FLIGHT_LOADER;
SHOW GRANTS TO ROLE FLIGHT_TRANSFORMER;
SHOW GRANTS TO ROLE FLIGHT_REPORTER;

SHOW GRANTS TO USER FLIGHT_DLT_USER;
SHOW GRANTS TO USER FLIGHT_DBT_USER;
SHOW GRANTS TO USER FLIGHT_STREAMLIT_USER;
