USE ROLE SYSADMIN;

CREATE WAREHOUSE IF NOT EXISTS FLIGHT_WH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE
    COMMENT = 'Warehouse för Flight Punctuality PoC';

CREATE DATABASE IF NOT EXISTS FLIGHT_DB
    COMMENT = 'Flight Punctuality Analytics';

CREATE SCHEMA IF NOT EXISTS FLIGHT_DB.RAW      COMMENT = 'Rådata från dlt';
CREATE SCHEMA IF NOT EXISTS FLIGHT_DB.STAGING  COMMENT = 'dbt staging-modeller';
CREATE SCHEMA IF NOT EXISTS FLIGHT_DB.MARTS    COMMENT = 'dbt dimensionsmodell för dashboarden';


USE ROLE USERADMIN;

CREATE ROLE IF NOT EXISTS FLIGHT_LOADER       COMMENT = 'dlt: laddar rådata';
CREATE ROLE IF NOT EXISTS FLIGHT_TRANSFORMER  COMMENT = 'dbt: transformerar data';
CREATE ROLE IF NOT EXISTS FLIGHT_REPORTER     COMMENT = 'Streamlit: läser marts';

USE ROLE SECURITYADMIN;

GRANT ROLE FLIGHT_LOADER      TO ROLE SYSADMIN;
GRANT ROLE FLIGHT_TRANSFORMER TO ROLE SYSADMIN;
GRANT ROLE FLIGHT_REPORTER    TO ROLE SYSADMIN;


GRANT USAGE ON WAREHOUSE FLIGHT_WH TO ROLE FLIGHT_LOADER;
GRANT USAGE ON WAREHOUSE FLIGHT_WH TO ROLE FLIGHT_TRANSFORMER;
GRANT USAGE ON WAREHOUSE FLIGHT_WH TO ROLE FLIGHT_REPORTER;

GRANT USAGE ON DATABASE FLIGHT_DB TO ROLE FLIGHT_LOADER;
GRANT USAGE ON DATABASE FLIGHT_DB TO ROLE FLIGHT_TRANSFORMER;
GRANT USAGE ON DATABASE FLIGHT_DB TO ROLE FLIGHT_REPORTER;


GRANT USAGE, CREATE TABLE ON SCHEMA FLIGHT_DB.RAW TO ROLE FLIGHT_LOADER;


GRANT USAGE ON SCHEMA FLIGHT_DB.RAW TO ROLE FLIGHT_TRANSFORMER;
GRANT SELECT ON ALL TABLES    IN SCHEMA FLIGHT_DB.RAW TO ROLE FLIGHT_TRANSFORMER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA FLIGHT_DB.RAW TO ROLE FLIGHT_TRANSFORMER;


GRANT USAGE, CREATE TABLE, CREATE VIEW ON SCHEMA FLIGHT_DB.STAGING TO ROLE FLIGHT_TRANSFORMER;
GRANT USAGE, CREATE TABLE, CREATE VIEW ON SCHEMA FLIGHT_DB.MARTS   TO ROLE FLIGHT_TRANSFORMER;


GRANT USAGE ON SCHEMA FLIGHT_DB.MARTS TO ROLE FLIGHT_REPORTER;
GRANT SELECT ON ALL TABLES    IN SCHEMA FLIGHT_DB.MARTS TO ROLE FLIGHT_REPORTER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA FLIGHT_DB.MARTS TO ROLE FLIGHT_REPORTER;
GRANT SELECT ON ALL VIEWS     IN SCHEMA FLIGHT_DB.MARTS TO ROLE FLIGHT_REPORTER;
GRANT SELECT ON FUTURE VIEWS  IN SCHEMA FLIGHT_DB.MARTS TO ROLE FLIGHT_REPORTER;


USE ROLE USERADMIN;

CREATE USER IF NOT EXISTS FLIGHT_DLT_USER
    PASSWORD = 'BYT_UT_1'
    DEFAULT_ROLE = FLIGHT_LOADER
    DEFAULT_WAREHOUSE = FLIGHT_WH
    DEFAULT_NAMESPACE = FLIGHT_DB.RAW
    MUST_CHANGE_PASSWORD = FALSE
    COMMENT = 'Servicekonto för dlt';

CREATE USER IF NOT EXISTS FLIGHT_DBT_USER
    PASSWORD = 'BYT_UT_2'
    DEFAULT_ROLE = FLIGHT_TRANSFORMER
    DEFAULT_WAREHOUSE = FLIGHT_WH
    DEFAULT_NAMESPACE = FLIGHT_DB.STAGING
    MUST_CHANGE_PASSWORD = FALSE
    COMMENT = 'Servicekonto för dbt';

CREATE USER IF NOT EXISTS FLIGHT_STREAMLIT_USER
    PASSWORD = 'BYT_UT_3'
    DEFAULT_ROLE = FLIGHT_REPORTER
    DEFAULT_WAREHOUSE = FLIGHT_WH
    DEFAULT_NAMESPACE = FLIGHT_DB.MARTS
    MUST_CHANGE_PASSWORD = FALSE
    COMMENT = 'Servicekonto för Streamlit';