USE ROLE SYSADMIN;

CREATE WAREHOUSE IF NOT EXISTS FLIGHT_WH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE
    COMMENT = 'Warehouse för Flight Punctuality PoC';

CREATE DATABASE IF NOT EXISTS FLIGHT_DB
    COMMENT = 'Flight Punctuality Analytics';

CREATE SCHEMA IF NOT EXISTS FLIGHT_DB.RAW      COMMENT = 'Rådata från dlt';
CREATE SCHEMA IF NOT EXISTS FLIGHT_DB.STAGING  COMMENT = 'dbt staging-modeller';
CREATE SCHEMA IF NOT EXISTS FLIGHT_DB.MARTS    COMMENT = 'dbt dimensionsmodell för dashboarden';


USE ROLE USERADMIN;

CREATE ROLE IF NOT EXISTS FLIGHT_LOADER       COMMENT = 'dlt: laddar rådata';
CREATE ROLE IF NOT EXISTS FLIGHT_TRANSFORMER  COMMENT = 'dbt: transformerar data';
CREATE ROLE IF NOT EXISTS FLIGHT_REPORTER     COMMENT = 'Streamlit: läser marts';

USE ROLE SECURITYADMIN;

GRANT ROLE FLIGHT_LOADER      TO ROLE SYSADMIN;
GRANT ROLE FLIGHT_TRANSFORMER TO ROLE SYSADMIN;
GRANT ROLE FLIGHT_REPORTER    TO ROLE SYSADMIN;